# Generated by Django 4.0.4 on 2022-05-15 15:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_chekoutaddress'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChekoutAddress',
            new_name='CheckoutAddress',
        ),
    ]
